# Generated by Django 6.0 on 2026-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите id сессии", max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="method_payment",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("stripe", "Stripe онлайн-оплата")],
                help_text="Выберите способ оплаты",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
