# Generated by Django 5.2.10 on 2026-01-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Отметка об активности подписки", verbose_name="Активная подписка"
            ),
        ),
    ]
